// Fallback config. Loaded after config.js — only sets CONFIG if the real file
// wasn't generated by the Actions workflow (e.g. local dev or missing secrets).
if (!window.CONFIG) {
  window.CONFIG = {
    primaryColor: "#0c3ff7",
    logoUrl: "./assets/wedigitek.png",
    faviconUrl: "./assets/favicon.ico"
  };
}
